# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 11:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_item_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.TextField(blank=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.Item')),
            ],
            options={
                'permissions': (('can_write_protocol', 'Can write protocol'),),
            },
        ),
    ]
