# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemprotocol',
            options={'default_permissions': (), 'permissions': (('can_write_protocol', 'Can write protocol'),)},
        ),
    ]
