# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-13 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('openslides_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectprotocol',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
